# Generated by Django 5.1.2 on 2025-11-16 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint'], name='api_usage_l_endpoin_133785_idx'), models.Index(fields=['symbol'], name='api_usage_l_symbol_170501_idx'), models.Index(fields=['created_at'], name='api_usage_l_created_c81af4_idx'), models.Index(fields=['ip_address'], name='api_usage_l_ip_addr_bfb878_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol (e.g., AAPL, MSFT)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator(code='invalid_symbol', message='Symbol can only contain uppercase letters, numbers, dots, and hyphens', regex='^[A-Z0-9.-]+$')])),
                ('name', models.CharField(help_text='Full company name', max_length=200)),
                ('search_count', models.IntegerField(default=0, help_text='Number of times this company has been searched')),
                ('last_searched', models.DateTimeField(auto_now=True, help_text='Last time this company was searched')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was first created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is still actively traded')),
                ('exchange', models.CharField(blank=True, help_text='Stock exchange (e.g., NASDAQ, NYSE)', max_length=50, null=True)),
                ('currency', models.CharField(default='USD', help_text='Trading currency', max_length=10)),
                ('last_data_refresh', models.DateTimeField(blank=True, help_text='When financial data was last refreshed for this company', null=True)),
            ],
            options={
                'verbose_name': 'Company Search',
                'verbose_name_plural': 'Company Searches',
                'db_table': 'company_searches',
                'ordering': ['-search_count', 'symbol'],
                'indexes': [models.Index(fields=['symbol'], name='company_sea_symbol_072be4_idx'), models.Index(fields=['search_count'], name='company_sea_search__6c4657_idx'), models.Index(fields=['last_searched'], name='company_sea_last_se_155a2c_idx'), models.Index(fields=['is_active'], name='company_sea_is_acti_bb7a92_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_symbol', message='Symbol can only contain uppercase letters, numbers, dots, and hyphens', regex='^[A-Z0-9.-]+$')])),
                ('statement_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cash_flow', 'Cash Flow Statement')], help_text='Type of financial statement', max_length=50)),
                ('period', models.DateField(help_text='Financial period/date for this statement')),
                ('data', models.JSONField(help_text='Complete financial data in JSON format')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this cache entry was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cache entry was created')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this cache entry is still valid')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this cache entry expires', null=True)),
                ('data_source', models.CharField(default='yfinance', help_text='Source of the financial data', max_length=100)),
                ('data_version', models.CharField(default='1.0', help_text='Version of data structure', max_length=20)),
            ],
            options={
                'verbose_name': 'Financial Statement Cache',
                'verbose_name_plural': 'Financial Statement Caches',
                'db_table': 'financial_statement_cache',
                'ordering': ['symbol', 'statement_type', '-period'],
                'indexes': [models.Index(fields=['symbol', 'statement_type'], name='financial_s_symbol_b5cded_idx'), models.Index(fields=['symbol', 'statement_type', 'period'], name='financial_s_symbol_a84053_idx'), models.Index(fields=['last_updated'], name='financial_s_last_up_fd94d4_idx'), models.Index(fields=['expires_at'], name='financial_s_expires_bfa091_idx'), models.Index(fields=['is_valid'], name='financial_s_is_vali_3f31bb_idx')],
                'unique_together': {('symbol', 'statement_type', 'period')},
            },
        ),
    ]
