"""
Django settings for fingenie_core project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

VECTOR_STORE_DIR = os.path.join(BASE_DIR, 'vector_stores')
if not os.path.exists(VECTOR_STORE_DIR):
    os.makedirs(VECTOR_STORE_DIR)
    
# Media files (uploaded PDFs will be stored here)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cv1)6=wq(z30$=mc5l*df0*7qvhd8v7x7m(3le!3%(k62zbge0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "fingenie-sz41.onrender.com",
    "fingenie-2exi.vercel.app",
    "localhost",
    "127.0.0.1",
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Required for sessions
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Must be before django apps
    'rest_framework',
]

EXTERNAL_APPS = [
    'apps.accounts',
    'apps.dataprocessor',
    'apps.stockgraph',
    'apps.chatbot',
    'apps.learning',
    'apps.sector_overview',
    'apps.trends',
    'apps.ai_insights',
    'apps.blog',
    'apps.company_search',
]

INSTALLED_APPS += EXTERNAL_APPS

# MIDDLEWARE - Order matters!
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST BE FIRST for CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Required for sessions
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================================
# CORS Configuration - CRITICAL for cross-origin authentication
# ============================================================================

# Development: Allow specific origins
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite default
    "http://127.0.0.1:5173",
    "https://fingenie-2exi.vercel.app",
    "https://fingenie-eight.vercel.app",
    "https://fingenie-sz41.onrender.com",
]

# CRITICAL: Must be True to allow cookies in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',  # Required for CSRF
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ============================================================================
# SESSION Configuration - CRITICAL FIX FOR HTTP DEVELOPMENT
# ============================================================================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = False

# CRITICAL FIX: For HTTP development (localhost without HTTPS)
# SameSite=None requires Secure=True, but Secure=True requires HTTPS
# Solution: Use SameSite=Lax for development (works on localhost)
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SECURE = False  # Must be False for HTTP
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JS access
SESSION_COOKIE_SAMESITE = 'Lax'  # Changed to Lax for HTTP development
SESSION_COOKIE_PATH = '/'

# ============================================================================
# CSRF Configuration
# ============================================================================

CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_AGE = 31449600  # 1 year
CSRF_USE_SESSIONS = False  # Store in cookie, not session

CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = False  # Must be False for HTTP
CSRF_COOKIE_HTTPONLY = False  # MUST be False so JavaScript can read it
CSRF_COOKIE_SAMESITE = 'Lax'  # Changed to Lax for HTTP development
CSRF_COOKIE_PATH = '/'

# Trusted origins for CSRF (allows POST requests from these origins)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://fingenie-2exi.vercel.app",
    "https://fingenie-eight.vercel.app",
    "https://fingenie-sz41.onrender.com",
]

# ============================================================================
# URLs and Templates
# ============================================================================

ROOT_URLCONF = 'fingenie_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fingenie_core.wsgi.application'

# ============================================================================
# Database
# ============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================================
# Authentication
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# Internationalization
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# Static files
# ============================================================================

STATIC_URL = 'static/'

# ============================================================================
# Default primary key field type
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Google OAuth
# ============================================================================

GOOGLE_OAUTH_CLIENT_ID = os.environ.get(
    'GOOGLE_OAUTH_CLIENT_ID', 
    '972027062493-i944gk25qhn7qj8ut7ebu6jdnpud8des.apps.googleusercontent.com'
)
# GOOGLE_API_KEY = os.environ.get(
#     'GOOGLE_API_KEY', 
#     'AIzaSyBqHvZ3wTzU8A-cXBYk4Pkt_j1548AODCg'
# )

# ============================================================================
# Logging Configuration
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'apps.accounts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'django.contrib.sessions': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
NEWS_API_KEY = "7a624852aa6a420aaeedf127d88a67f8"
LOGIN_URL = "/accounts/api/login/"

# ============================================================================
# DEPLOYMENT NOTES
# ============================================================================
"""
THE LOCALHOST CROSS-ORIGIN COOKIE PROBLEM:
------------------------------------------
When your React app (localhost:3000) calls Django (127.0.0.1:8000), browsers treat
this as cross-origin even though both are localhost. 

THE ISSUE:
- SameSite=None requires Secure=True
- Secure=True requires HTTPS
- localhost doesn't have HTTPS
- Result: Cookies won't be set

SOLUTION FOR DEVELOPMENT:
Use SameSite=Lax with localhost. This works because:
- Modern browsers treat localhost specially
- SameSite=Lax allows cookies from the same site
- localhost and 127.0.0.1 are treated as the same site in many browsers

IMPORTANT: Run Django on localhost (not 127.0.0.1):
$ python manage.py runserver localhost:8000

Then in your React app, use:
const API_URL = 'http://localhost:8000';

ALTERNATIVE SOLUTIONS:
1. Use a proxy in React (recommended for production-like setup)
2. Use HTTPS in development with self-signed certificates
3. Deploy both to the same domain/subdomain

FOR PRODUCTION WITH HTTPS:
- Change SESSION_COOKIE_SECURE = True
- Change CSRF_COOKIE_SECURE = True  
- Can use SameSite='Lax' or 'Strict'
"""