# Generated by Django 5.1.2 on 2025-11-08 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Unknown Company', max_length=255)),
                ('ticker_symbol', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField(default='{"pros": [], "cons": [], "financial_health_summary": ""}')),
                ('ratios', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'financial_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
