# Generated by Django 5.1.2 on 2025-11-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Financial Report', 'verbose_name_plural': 'Financial Reports'},
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='ratios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
