# Generated by Django 5.1.2 on 2025-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0002_alter_financialreport_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialreport',
            old_name='summary',
            new_name='extracted_data',
        ),
        migrations.RenameField(
            model_name='financialreport',
            old_name='ratios',
            new_name='ratios_data',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='summary_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
