# Generated by Django 5.1.2 on 2025-11-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0003_rename_summary_financialreport_extracted_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='extracted_data',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='ratios_data',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='summary_data',
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='ticker_symbol',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
