# Generated by Django 5.1.2 on 2025-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0004_remove_financialreport_extracted_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='ratios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
