# Generated by Django 5.1.2 on 2025-11-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocessor', '0005_financialreport_ratios_financialreport_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='pdf_original_name',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded PDF', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='uploaded_pdf',
            field=models.FileField(blank=True, help_text='Uploaded balance sheet PDF file', null=True, upload_to='balance_sheets/'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
