# Generated by Django 5.1.2 on 2025-11-15 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Investments', 'Investments'), ('Personal Finance', 'Personal Finance'), ('Market Analysis', 'Market Analysis'), ('Future of Finance', 'Future of Finance')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.TextField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='blogbookmark',
            index=models.Index(fields=['user', 'post'], name='blog_blogbo_user_id_610a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogbookmark',
            index=models.Index(fields=['post'], name='blog_blogbo_post_id_7575f1_idx'),
        ),
        migrations.AddIndex(
            model_name='blogbookmark',
            index=models.Index(fields=['created_at'], name='blog_blogbo_created_8ccfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='bloglike',
            index=models.Index(fields=['user', 'post'], name='blog_blogli_user_id_cebb67_idx'),
        ),
        migrations.AddIndex(
            model_name='bloglike',
            index=models.Index(fields=['post'], name='blog_blogli_post_id_87efa2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published', 'created_at'], name='blog_blogpo_publish_77f135_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='blog_blogpo_categor_481d67_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author'], name='blog_blogpo_author__0d5a17_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['created_at'], name='blog_blogpo_created_ddb27d_idx'),
        ),
    ]
