# Generated by Django 5.1.2 on 2025-11-16 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_remove_blogpost_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.RemoveIndex(
            model_name='blogbookmark',
            name='blog_blogbo_user_id_610a1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogbookmark',
            name='blog_blogbo_post_id_7575f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogbookmark',
            name='blog_blogbo_created_8ccfdd_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloglike',
            name='blog_blogli_user_id_cebb67_idx',
        ),
        migrations.RemoveIndex(
            model_name='bloglike',
            name='blog_blogli_post_id_87efa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_publish_77f135_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_categor_481d67_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_author__0d5a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_created_ddb27d_idx',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Investments', 'Investments'), ('Personal Finance', 'Personal Finance'), ('Market Analysis', 'Market Analysis'), ('Future of Finance', 'Future of Finance')], default='Investments', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.TextField(max_length=300),
        ),
    ]
