# Generated by Django 5.1.2 on 2025-11-16 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetComparison',
            fields=[
                ('comparison_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company1_name', models.CharField(default='Company 1', max_length=255)),
                ('company2_name', models.CharField(default='Company 2', max_length=255)),
                ('comparison_result', models.JSONField(blank=True, default=dict)),
                ('company1_metrics', models.JSONField(blank=True, default=dict)),
                ('company2_metrics', models.JSONField(blank=True, default=dict)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance Sheet Comparison',
                'verbose_name_plural': 'Balance Sheet Comparisons',
                'db_table': 'balance_sheet_comparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
